### PR TITLE
Change to manual dispatch, where images will get stored

### PR DESCRIPTION
**Pull request by jonathan-taylor**

### CODE REVIEW

**Comment by jonathan-taylor** [comment]
Now that I see what a docker user can get, and the minimal workflow file this seems to make sense.

I'd like to have it manual for now, as that is how docs etc are updated. If we start publishing more I might use the `release` event.

**Comment by jonathan-taylor** [comment]
I have the docker image building and running now.

Ch10 is *very* slow when I use `docker run`. I guess the VM that docker gets is somewhat slower than running in a standard conda env.

**Comment by jonathan-taylor** [comment]
About 4min per epoch on the 2-layer MNIST model when running on my Mac....

Maybe more advanced docker users know how to tweak resources given to the docker image... 

Still, compares favorably to `binder` on `Ch10` which fails before starting `MNIST`

**Comment by tschm** [comment]
Interesting, I assume you have docker desktop installed on your Apple M1 machine. You could allocate more resources to docker (when it runs)

**Comment by jonathan-taylor** [comment]
> Interesting, I assume you have docker desktop installed on your Apple M1 machine. You could allocate more resources to docker (when it runs)

Yes, but this is something for people with docker experience to worry about. Running in a virtualenv is much faster without explicitly worrying about resources.

**Pull request merged**
